# Generated by Django 2.1.5 on 2019-02-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rddt_main', '0002_auto_20190203_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reddituser',
            name='about',
            field=models.TextField(blank=True, max_length=400, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='reddituser',
            name='email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Электронная почта'),
        ),
    ]
