# Generated by Django 2.1.5 on 2019-02-11 14:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rddt_main', '0004_auto_20190208_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('publish_date',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish_date',)},
        ),
        migrations.AlterField(
            model_name='comment',
            name='replied_comment',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rddt_main.Comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(max_length=5000, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='reddituser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Пользователь с таким именем уже существует'}, max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\dA-zА-я_\\-\\.]+$', 'Имя пользователя должно состоять из цифр, латиницы, кириллицы или знаков "_-."')], verbose_name='Имя пользователя'),
        ),
    ]
